version: 1.0
templates:
  - name: maven-java-11
    spec:
      environment:
        docker.image: maven:3.8.1-openjdk-11
        command: mvn clean test --no-transfer-progress -P suite=${SUITE} -P ${tread_count}
      parameters:
        env:
          - name: VAR
            defaultValue: false
            type: boolean
        commandVars:
          - name: tread_count
            defaultValue: 1
            type: integer
  - spec:
      environment:
        docker.image: openjdk:11
        command: ./gradlew clean test
      parameters:
        env:
          - name: locale
            defaultValue: en_us
launchers:
  - name: API Acceptance Suite
    template: maven-java-11
    parameters:
      commandVars:
        - name: SUITE
          defaultValue: api
